
(function() {
  "use strict";

  function init() {
    document.getElementById("pressOne").addEventListener("click", firstText);
    document.getElementById("pressTwo").addEventListener("click", secondText);
    document.getElementById("pressThree").addEventListener("click", thirdText);
  }

  function firstText() {
    //test generated by https://www.lipsum.com/
    var loremIpsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia turpis ante, eu laoreet ante eleifend in. Donec aliquet laoreet massa interdum feugiat. Duis et sem mollis, condimentum risus vel, pulvinar neque. Praesent felis turpis, lobortis non arcu a, fermentum cursus turpis. Cras bibendum sollicitudin dapibus. Praesent et lacus sed magna venenatis rutrum pretium a ligula. Aenean mi tellus, tincidunt sed est quis, egestas consequat justo. Aliquam erat volutpat. Nullam non lacus in orci rutrum placerat. Quisque ut ligula ornare, ultrices ipsum eu, vestibulum dolor. Nulla id tellus mi. Vivamus sed ultrices ex. Donec at pharetra justo. Aenean eget elit in sem accumsan convallis at a magna.\nCras iaculis turpis orci, eu pharetra turpis semper at. Donec in dolor urna. Donec aliquam mauris quis mi vulputate, non rhoncus lorem molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam tincidunt nulla dignissim ipsum laoreet vulputate. Sed mollis est et eleifend pellentesque. Mauris gravida nisl at lectus finibus fringilla. In arcu est, sodales quis vulputate in, suscipit a erat. Quisque commodo maximus turpis, in ultricies arcu mollis ut. Maecenas nec metus non enim ultricies dignissim ac et turpis. In a enim ipsum. \nAliquam a tincidunt ex. Sed dui lectus, pulvinar id ultricies id, commodo eget tellus. Donec vitae ante tincidunt, ultricies massa vitae, blandit risus. Cras euismod nunc ac ex vestibulum, sit amet dictum nulla finibus. Sed commodo, sem at iaculis aliquet, nisl augue sodales turpis, in rhoncus ligula dui at risus. Maecenas imperdiet facilisis nunc, ut bibendum purus fringilla vel. Etiam interdum laoreet rutrum. Etiam viverra elit sit amet nulla elementum ullamcorper. Quisque mauris mi, fringilla et augue mattis, semper elementum massa. Nunc et tincidunt metus, vel ullamcorper arcu. Vivamus id pellentesque tortor, vitae ullamcorper erat. Cras vel mauris felis. Nunc aliquam suscipit lacus sit amet maximus. Curabitur eget vestibulum purus.\nIn iaculis, mi et aliquet hendrerit, arcu quam interdum massa, sed molestie dolor ante sodales diam. Integer sollicitudin, elit vitae auctor varius, leo nibh porttitor justo, quis ultricies velit urna eget lorem. Integer sit amet facilisis magna. Aenean id odio libero. Quisque volutpat sagittis mauris, ac ullamcorper urna. Nunc pretium eros sit amet mauris commodo tempor. Aliquam interdum urna tristique imperdiet malesuada. Integer eu leo sit amet dolor bibendum elementum. In elementum nisi in urna condimentum tempus. Sed sed ex dapibus, convallis nisl non, dignissim elit. Nulla a mollis turpis. Vivamus eu dolor et quam ultricies facilisis et a ex. Aliquam eget velit ligula. Quisque eleifend malesuada nisl. Phasellus placerat facilisis eros ut elementum. Proin venenatis pharetra mi tincidunt tincidunt.";

    var text = document.getElementById("text");
    text.innerHTML = loremIpsum;
    return false;
  }

  function secondText() {
    //song lyrics documented here : https://en.wikipedia.org/wiki/99_Bottles_of_Beer
    var beer = "99 bottles of beer on the wall, 99 bottles of beer.\nTake one down, pass it around, 98 bottles of beer on the wall\n\n98 bottles of beer on the wall, 98 bottles of beer.\nTake one down, pass it around, 97 bottles of beer on the wall\n\n97 bottles of beer on the wall, 97 bottles of beer.\nTake one down, pass it around, 96 bottles of beer on the wall\n\n96 bottles of beer on the wall, 96 bottles of beer.\nTake one down, pass it around, 95 bottles of beer on the wall";
    var text = document.getElementById("text");
    text.innerHTML = beer;
    return false;
  }

  function thirdText() {
    var third = "this is the third thing";
    var text = document.getElementById("text");
    text.innerHTML = third;
    return false;
  }
  window.addEventListener('load', init, false);


})();

